### ISSUE TITLE
theme is not exported from react-trip-date

### ISSUE THREAD

**Issue by ionescho** [samsam-ahmadi/react-trip-date#13]
![image](https://user-images.githubusercontent.com/5604479/113299000-14527580-9305-11eb-8af3-39d89d7f8fe9.png)

**Comment by samsam-ahmadi** [comment]
@ionescho Hi, which version are you using?

**Comment by ionescho** [comment]
@samsam-ahmadi the latest one, just installed it with npm install --save react-trip-date and it came as 1.5.1.

**Comment by samsam-ahmadi** [comment]
@ionescho  If you are following the old documentation is wrong, In the new version don't need to get the theme from the package and put it to ThemeProvider we handle it in the inner of the component. 
But yes I should export the type of theme.

In this version, you need to create an object and fill it with this structure: 

```js
  const theme = {
    primary: {
      light: "#757ce8",
      main: "#3f50b5",
      dark: "#002884",
    },
    grey: {
      700: "#707070",
      900: "#1b1b1d",
    },
    background: {
      default: "#f5f5f5",
    },
    text: {
      disabled: "#BABABA",
    },
  };

  <DatePicker theme={theme} onChange={dates => console.log("dates", dates)} />


```

**Comment by ionescho** [comment]
Alright, clear.
This page needs to be updated: https://reactjsexample.com/a-date-range-picker-for-reactjs/

Thanks

**Comment by samsam-ahmadi** [comment]
@ionescho  NP. I couldn't find a way to tell them update their page. :((
