### ISSUE TITLE
[BUG] - Setting startOfWeek={1} on <RangePicker /> creates an extra empty row at the beginning of the month

### ISSUE THREAD

**Issue by ionescho** [samsam-ahmadi/react-trip-date#15]
![image](https://user-images.githubusercontent.com/5604479/113413657-d700ed00-93c3-11eb-8e51-51dbfe9b6d27.png)

**Comment by ionescho** [comment]
A weird workaround for me was setting startOfWeek={8}

**Comment by samsam-ahmadi** [comment]
@ionescho  I think startOfWeek shouldn't be more than 3, for now, we didn't limit that, but in the future, we do it.

The issue in this react-trip-date@1.5.2  has been fixed.
