### ISSUE TITLE
[Feature] add min range

### ISSUE THREAD

**Issue by metalmaninfr** [samsam-ahmadi/react-trip-date#17]
## Problem

it's almost impossible to create a custom function that handles both start and end date on the range calendar

## Solution

add min range prop to calendar or return selected `from` & `to` on the onChange prop

## Community Benefits

be able to use calendar to set a minimum range of days

**Comment by davidvenin** [comment]
I think we need to add the first click in the onChange (to get the start) et then de end date.

**Comment by samsam-ahmadi** [comment]
@metalmaninfr  Currently we are returning the from and to in onChange, 
But if you need to get `from` after a click, we can do it.

**Comment by davidvenin** [comment]
That's exactly what we are looking for. I think it's from Day, we need to add a first condition if dayjs(from) && to === "" to call setSelectedDays() with at least from at the first click. Maybe I'm wrong.

**Comment by samsam-ahmadi** [comment]
@davidvenin 
Ok, Please check this version `1.6.3`

**Comment by metalmaninfr** [comment]
awesome thank you :)
