### ISSUE TITLE
[Feature] Header months are unknown

### ISSUE THREAD

**Issue by metalmaninfr** [samsam-ahmadi/react-trip-date#24]
## Problem

is there a way to know which month is selected in the header ?

**Comment by samsam-ahmadi** [comment]
@metalmaninfr 
Please check onRangeDateInScreen props.

**Comment by metalmaninfr** [comment]
https://codesandbox.io/s/angry-stonebraker-1wxr4

this seems to create an infinite loop

**Comment by samsam-ahmadi** [comment]
@metalmaninfr  I checked your code, you pass initialMonthAndYear to the calendar, and Also change it after the onRangeDateInScreen called, Please don't pass initialMonthAndYear to the calendar that makes a loop over the application.

**Comment by metalmaninfr** [comment]
okay thank you for confirming, that it was an error on my side :)
