### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by ianemv** [samsam-ahmadi/react-trip-date#3]
## Problem

- Localization
     Allow the calendar to set language
- No start of the week. Only format the week headings
- No option to set the format of Month year heading (Month - Year)

## Solution

- Add props for months, weeks for desired language (defaults to English)
--For instance in Finnish, I will just pass the array of Months and Weeks that could be one
--Or have an array of months and years of common languages use
- Add props for start of the week (defaults to Sunday)
- Add props for month and year display format (set default to Month-Year)

## Community Benefits

It will be use to apply their use-case.

**Comment by samsam-ahmadi** [comment]
@ianemv  Please have a look again, this package updated, and I think those things ready to use.
