### ISSUE TITLE
Vanilla JS

### ISSUE THREAD

**Issue by MR-Mostafa** [samsam-ahmadi/react-trip-date#30]
Hi Samsam,
Is there any version of this library that does not have the ReactJS dependency? (Just use vanilla Js)

If not:
1- Do you have a plan to do this?
2- Do you have a vanilla **date range picker** that does not any dependency (like jquery or react and etc)?  (another library)

Thanks.

**Comment by samsam-ahmadi** [comment]
Hi @MR-Mostafa Jan, 

1: Actually no, I don't have any plan for it.   
2: Sorry, Again no I don't have it, but maybe you can find similar things in the [codesandbox](https://codesandbox.io/search?query=datepicker%20vanilla&page=1&configure%5BhitsPerPage%5D=12)
