### ISSUE TITLE
[BUG] `react-scripts` causing security audit errors

### ISSUE THREAD

**Issue by nick-heard** [samsam-ahmadi/react-trip-date#38]
The current version of `react-scripts` (4.0.3) is causing security audit errors (`npm audit`)

## Expected Behavior

No errors are shown from `npm audit` (due to this package)

## Current Behavior

`npm audit` is outputting security errors.  Here's an example of one (getting 7 from this package total)

```
ansi-html  <=0.0.7
Severity: high
Uncontrolled Resource Consumption in ansi-html - https://github.com/advisories/GHSA-whgm-jr23-g3j9
fix available via `npm audit fix --force`
Will install react-trip-date@0.0.3, which is a breaking change
node_modules/ansi-html
  @pmmmwh/react-refresh-webpack-plugin  <=0.5.0-rc.6
  Depends on vulnerable versions of ansi-html
  node_modules/react-trip-date/node_modules/@pmmmwh/react-refresh-webpack-plugin
    react-scripts  >=0.10.0-alpha.328cb32e
    Depends on vulnerable versions of @pmmmwh/react-refresh-webpack-plugin
    Depends on vulnerable versions of @svgr/webpack
    Depends on vulnerable versions of optimize-css-assets-webpack-plugin
    Depends on vulnerable versions of react-dev-utils
    Depends on vulnerable versions of webpack
    Depends on vulnerable versions of webpack-dev-server
    node_modules/react-scripts
    node_modules/react-trip-date/node_modules/react-scripts
      react-trip-date  >=1.1.0
      Depends on vulnerable versions of react-scripts
      node_modules/react-trip-date
  webpack-dev-server  2.0.0-beta - 4.7.2
  Depends on vulnerable versions of ansi-html
  Depends on vulnerable versions of chokidar
  Depends on vulnerable versions of selfsigned
  Depends on vulnerable versions of yargs
  node_modules/react-trip-date/node_modules/webpack-dev-server
```

## Possible Solutions
There are a few:
* The fastest solution is to make `react-scripts` a dev-dependency.  This isn't _perfect_ because `react-scripts` is meant to be a dependency due to included pollyfills https://github.com/facebook/create-react-app/issues/2696

* Update `react-scripts` to v 5.0.0 .  This is actually a huge pain https://github.com/facebook/create-react-app/issues/11756 and there are no guarantees this issue won't happen in the future

* Really the best solution is to remove this dependency altogether.  I'm actually not entirely sure why it's needed but this may take some work and project reorganization

## Your Environment

- React Version: 17.0.2
- npm Version: 8.5.2

## Additional Comments
None of the other packages in my react project currently are using `react-scripts` as a dependency
Also - I love this library 😄

**Comment by nick-heard** [comment]
I don't have experience with the flow around publishing packages so don't feel comfortable putting up review for this.  Basically I had to commit the dist folder along with making react-scripts a dev dependency https://github.com/nick-heard/react-trip-date/tree/reactScriptsUpdate

Was able to test and got everything to work

The situation was actually worse than I thought though.  The use of the old react scripts version as a dependency was a crutch for me fixing all of the upgrade issues

For example:
My project needed the `assert` package because it's no longer provided by react scripts
the dependency flow looked like this
My project -> react-trip-date -> react-script v4 -> assert

Once react-script was removed as as a dependency the assert package was no longer there so I had to add it manually

I would have had to do the same thing if I were to remove react-trip-date from my app

I don't really know whether to call this a breaking change or not

**Comment by samsam-ahmadi** [comment]
@nick-heard  Hey nick, 
You shouldn't remove dist from the .gitignore, 

As you mentioned that if we want to upgrade it, it makes some issues. 
I decided to just upgrade the CRA instead of removing it for now. 

But when we upgrade it, it makes some issues in the package. for example storybook doesn't work.
I try to fix it.

**Comment by samsam-ahmadi** [comment]
@nick-heard  I know it's too late, but I updated the packages. 
Thanks for your waiting. :)
