### ISSUE TITLE
[BUG] Range Picker Doesn't Highlights The Dates Between Selected Date Range

### ISSUE THREAD

**Issue by naumanzchaudhry** [samsam-ahmadi/react-trip-date#4]
## Expected Behavior

When user selects a start date from range picker and moves to select the end date. It should highlight the intermediate date nodes.

## Current Behavior

Dates between the dates selected are not highlighted.

## Your Environment

React 16.9.0
Next 9,0.4

**Comment by naumanzchaudhry** [comment]
@samsam-ahmadi Seems to work here https://killthejs.com/react-trip-date/?path=/story/range-picker--all-props

RangePicker is behaving more like simple date picker.

**Comment by samsam-ahmadi** [comment]
Hi @naumanzchaudhry, sorry for the late answer. 
I've been working on a new version of it.
If you want, you can help me with this at Develop branch.

**Comment by samsam-ahmadi** [comment]
Hi @naumanzchaudhry, I fixed it in the new Version. 1.3.0.
Also in this version, we had some new props and the performance got better
