### ISSUE TITLE
[BUG] while numberOfSelectableDays=1, handleChange is not working

### ISSUE THREAD

**Issue by ArronHsiao** [samsam-ahmadi/react-trip-date#5]
Hi, When I set numberOfSelectableDays=1, handleChange is not working.

  handleChange = date => {
    console.log(date)
  }

no date will be recorded

**Comment by samsam-ahmadi** [comment]
@ArronHsiao  Hi Thanks for your reporting, I fixed it in the new Version. [1.3.0](https://www.npmjs.com/package/react-trip-date)
