### ISSUE TITLE
[Feature] react 18 support

### ISSUE THREAD

**Issue by sergei-lobanov** [samsam-ahmadi/react-trip-date#53]
Hello @samsam-ahmadi, could you please add react 18 support?

If there are no issues at all, should be enough to add it to the peer dependency

**current warnings:**
warning " > react-trip-date@1.12.0" has incorrect peer dependency "react@^17.0.1".
warning " > react-trip-date@1.12.0" has incorrect peer dependency "react-dom@^17.0.1".
warning "react-trip-date > styled-components@5.3.6" has unmet peer dependency "react-is@>= 16.8.0".

**Comment by samsam-ahmadi** [comment]
Hello @sergei-lobanov , 
Thanks for it. I will look at this to find any solution to can work with both versions.
