### ISSUE TITLE
[BUG] Can't resolve 'jalaliday'

### ISSUE THREAD

**Issue by sergei-lobanov** [samsam-ahmadi/react-trip-date#58]
When the library version was updated from 1.12.1 to 1.13.0 the build is failed with the error

## Expected Behavior
success build

## Current Behavior
build is failed with the next error
Module not found: Error: Can't resolve 'jalaliday' in '/var/jenkins_home/src/Common/components/react-trip-date/libs'

## Your Environment

- React Version: 18

## Additional Comments

I've tried to do clean up installation removing yarn.lock and generate it again, but it doesn't work.
I don't see anything about jalaliday in the changelog, but I've noticed that the dependency was removed in 1.13.0

![ScreenShot 02062023--at 14 58 04@2x](https://github.com/samsam-ahmadi/react-trip-date/assets/61283963/19a17527-c863-4459-8861-2cf464b31319)

**Comment by samsam-ahmadi** [comment]
@sergei-lobanov Thanks for reporting, 
Would you please check this demo application? 
https://stackblitz-starters-ro6npi.stackblitz.io
It doesn't have any issue with this version. 
Please clear the cache and test it again.

**Comment by sergei-lobanov** [comment]
@samsam-ahmadi I did a full clean up of node modules and lock file + cleared the cache, but nothing changed, the same issue.
Also if I search in the project folder I see that react-trip-date use a lot jalaliday inside the module.
Any idea how to fix it? And did you remove it completely or just removed the module from dependency? 

![ScreenShot 05062023--at 18 49 21@2x](https://github.com/samsam-ahmadi/react-trip-date/assets/61283963/4ba56337-3bc1-4da5-9dd7-34a613aff258)

**Comment by samsam-ahmadi** [comment]
@sergei-lobanov  Please give me more time to investigate,  Would you please downgrade until I check it and then I will let you know. Thanks.

**Comment by samsam-ahmadi** [comment]
@sergei-lobanov Please upgrade to v1.13.1.
