### ISSUE TITLE
[BUG]Wrong export index.ts

### ISSUE THREAD

**Issue by mebrahemi** [samsam-ahmadi/react-trip-date#7]
hi
export { default as DatePicker } from './calendar/date-picker';
export { default as RangePicker } from './calendar/date-picker'; // <------- must be export { default as RangePicker } from './calendar/range-picker'
...
becuase of this, RangePicker doesn't work.

**Comment by samsam-ahmadi** [comment]
Hi @mebrahemi, Yeah sorry about that, I had busy days and couldn't upgrade this package, But I will look at this and will fix the problems.

Thanks for your help and feel free to create PR.

**Comment by mebrahemi** [comment]
Thank you so much.
